server:
  port: 9991

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: wang1129
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      max-idle: 10
      min-idle: 5
      max-wait-millis: 10000
      initial-size: 5
      
  jackson:
    time-zone: Asia/Shanghai
    default-property-inclusion: NON_NULL
    deserialization:
      fail-on-unknown-properties: false
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: 'com.criss.wang.entity'